name: Test Suite e2e

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/test-suite.yml
      - apps/bare-expo/**
      - apps/test-suite/**
      - packages/**
      - yarn.lock
  pull_request:
    paths:
      - .github/workflows/test-suite.yml
      - apps/bare-expo/**
      - apps/test-suite/**
      - packages/**
      - yarn.lock
      # Ignore Expo CLI for now...
      - '!packages/@expo/cli/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  #  ios-build:
  #    runs-on: macos-15
  #    steps:
  #      - name: ğŸ‘€ Checkout
  #        uses: actions/checkout@v5
  #        with:
  #          submodules: true
  #      - name: ğŸ—ï¸ Setup Bun
  #        uses: oven-sh/setup-bun@v2
  #        with:
  #          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
  #          # TODO(cedric): swap `latest` back once the issue is resolved
  #          bun-version: latest
  #      - name: ğŸ”¨ Switch to Xcode 16.4
  #        run: sudo xcode-select --switch /Applications/Xcode_16.4.app
  #      - name: ğŸº Install required tools
  #        run: |
  #          brew install watchman || true
  #      - name: â• Add `bin` to GITHUB_PATH
  #        run: echo "$(pwd)/bin" >> $GITHUB_PATH
  #      - name: ğŸ’ Setup Ruby and install gems
  #        uses: ruby/setup-ruby@v1
  #        with:
  #          bundler-cache: true
  #          ruby-version: 3.2.2
  #      - name: â™»ï¸ Restore caches
  #        uses: ./.github/actions/expo-caches
  #        id: expo-caches
  #        with:
  #          yarn-workspace: 'true'
  #          yarn-tools: 'true'
  #          bare-expo-pods: 'true'
  #      - name: ğŸ§¶ Install node modules in root dir
  #        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
  #        run: yarn install --frozen-lockfile
  #      - name: ğŸ•µï¸ Debug CocoaPods lockfiles
  #        run: git diff Podfile.lock Pods/Manifest.lock
  #        working-directory: apps/bare-expo/ios
  #        continue-on-error: true
  #      - name: âš›ï¸ Display React Native config
  #        run: yarn expo-modules-autolinking react-native-config --platform ios
  #        working-directory: apps/bare-expo
  #      - name: ğŸŒ³ Display pod environment
  #        run: pod env
  #        working-directory: apps/bare-expo/ios
  #      - name: ğŸ¥¥ Install pods in apps/bare-expo/ios
  #        if: steps.expo-caches.outputs.ios-pods-hit != 'true'
  #        run: pod install
  #        env:
  #          RCT_USE_PREBUILT_RNCORE: 1
  #          RCT_USE_RN_DEP: 1
  #        working-directory: apps/bare-expo/ios
  #      - name: ğŸ—ï¸ Build iOS project (bare-expo)
  #        run: ./scripts/start-ios-e2e-test.ts --build
  #        working-directory: apps/bare-expo
  #        timeout-minutes: 55
  #        env:
  #          EXPO_DEBUG: 1
  #          NODE_ENV: production
  #      - name: ğŸ“¸ Upload builds
  #        uses: actions/upload-artifact@v4
  #        with:
  #          name: bare-expo-ios-builds
  #          path: apps/bare-expo/ios/build/BareExpo.app
  #      - name: ğŸ”” Notify on Slack
  #        uses: 8398a7/action-slack@v3
  #        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_ios }}
  #        with:
  #          channel: '#expo-ios'
  #          status: ${{ job.status }}
  #          fields: job,message,ref,eventName,author,took
  #          author_name: Test Suite e2e (iOS)

  ios-test-e2e:
    # needs: ios-build
    runs-on: macos-15
    steps:
      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: ğŸ—ï¸ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest
      - name: â• Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: ğŸŒ  Download builds from previous run
        uses: actions/download-artifact@v4
        with:
          name: bare-expo-ios-builds
          path: apps/bare-expo/ios/build/BareExpo.app
          run-id: 17638805817
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: ğŸº Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      - name: â™»ï¸ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
      - name: ğŸ§¶ Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ğŸ§ª Run e2e tests (bare-expo)
        run: ./scripts/start-ios-e2e-test.ts --test
        working-directory: apps/bare-expo
        timeout-minutes: 30
      - name: ğŸ“¸ Store testing artifacts
        if: always()
        uses: actions/upload-artifact@v4
        id: upload-artifacts
        with:
          name: bare-expo-artifacts-ios
          path: |
            ~/.maestro/tests/**/*
          #            ~/Library/Logs/maestro/**/*
          overwrite: true
      - name: ğŸ”— Artifacts URL ${{ steps.upload-artifacts.outputs.artifact-url }}
        if: always()
        run: |
          echo "Artifacts URL: ${{ steps.upload-artifacts.outputs.artifact-url }}"
      - name: ğŸ”” Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_ios }}
        with:
          channel: '#expo-ios'
          job_name: 'Test Suite e2e (iOS)'
          artifact_url: ${{ steps.upload-artifacts.outputs.artifact-url }}

  #  android-build:
  #    runs-on: ubuntu-24.04
  #    env:
  #      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
  #      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=4096m"
  #    steps:
  #      - name: ğŸ‘€ Checkout
  #        uses: actions/checkout@v5
  #        with:
  #          submodules: true
  #      - name: ğŸ§¹ Cleanup GitHub Linux runner disk space
  #        uses: ./.github/actions/cleanup-linux-disk-space
  #      - name: ğŸ—ï¸ Setup Bun
  #        uses: oven-sh/setup-bun@v2
  #        with:
  #          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
  #          # TODO(cedric): swap `latest` back once the issue is resolved
  #          bun-version: latest
  #      - name: ğŸ”¨ Use JDK 17
  #        uses: actions/setup-java@v4
  #        with:
  #          distribution: 'temurin'
  #          java-version: '17'
  #      - name: â• Add `bin` to GITHUB_PATH
  #        run: echo "$(pwd)/bin" >> $GITHUB_PATH
  #      - name: â™»ï¸ Restore caches
  #        uses: ./.github/actions/expo-caches
  #        id: expo-caches
  #        with:
  #          gradle: 'true'
  #          yarn-workspace: 'true'
  #          yarn-tools: 'true'
  #          react-native-gradle-downloads: 'true'
  #      - name: ğŸ§¶ Install workspace node modules
  #        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
  #        run: yarn install --frozen-lockfile
  #      - name: âš›ï¸ Display React Native config
  #        run: yarn expo-modules-autolinking react-native-config --platform android
  #        working-directory: apps/bare-expo
  #      - name: ğŸ—ï¸ Gradle prebuild for Android project (workaround to fix build error)
  #        run: ./gradlew preBuild
  #        working-directory: apps/bare-expo/android
  #      - name: ğŸ—ï¸ Build Android project (bare-expo)
  #        run: ./scripts/start-android-e2e-test.ts --build
  #        working-directory: apps/bare-expo
  #        timeout-minutes: 35
  #        env:
  #          EXPO_DEBUG: 1
  #          NODE_ENV: production
  #      - name: ğŸ“¸ Upload builds
  #        uses: actions/upload-artifact@v4
  #        with:
  #          name: bare-expo-android-builds
  #          path: apps/bare-expo/android/app/build/outputs/apk
  #      - name: ğŸ”” Notify on Slack
  #        uses: 8398a7/action-slack@v3
  #        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_android }}
  #          MATRIX_CONTEXT: ${{ toJson(matrix) }}
  #        with:
  #          channel: '#expo-android'
  #          status: ${{ job.status }}
  #          fields: job,message,ref,eventName,author,took
  #          author_name: Test Suite e2e (Android)

  android-test-e2e:
    # needs: android-build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        api-level: [36]
    steps:
      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v5
      - name: ğŸ—ï¸ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest
      - name: ğŸŒ  Download builds from previous run
        uses: actions/download-artifact@v4
        with:
          name: bare-expo-android-builds
          path: apps/bare-expo/android/app/build/outputs/apk
          run-id: 17638805817
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: ğŸº Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      - name: â™»ï¸ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
      - name: ğŸ§¶ Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: ğŸ§ª Run e2e tests (bare-expo)
        uses: ./.github/actions/use-android-emulator
        with:
          avd-api: ${{ matrix.api-level }}
          avd-name: avd-${{ matrix.api-level }}
          script: ./scripts/start-android-e2e-test.ts --test
          working-directory: ./apps/bare-expo
      - name: ğŸ“¸ Store testing artifacts
        if: always()
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bare-expo-artifacts-android
          path: |
            ~/.maestro/tests/**/*
          #            ~/Library/Logs/maestro/**/* # probably doesn't exist on Android runners
          overwrite: true
      - name: ğŸ”— Artifacts URL ${{ steps.upload-artifacts.outputs.artifact-url }}
        if: always()
        run: |
          echo "Artifacts URL: ${{ steps.upload-artifacts.outputs.artifact-url }}"
      - name: ğŸ”” Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_android }}
        with:
          channel: '#expo-android'
          job_name: 'Test Suite e2e (Android)'
          artifact_url: ${{ steps.upload-artifacts.outputs.artifact-url }}
